/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PatharAmbulanceWlList {
    }
}
declare global {
    interface HTMLPatharAmbulanceWlListElement extends Components.PatharAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLPatharAmbulanceWlListElement: {
        prototype: HTMLPatharAmbulanceWlListElement;
        new (): HTMLPatharAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "pathar-ambulance-wl-list": HTMLPatharAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface PatharAmbulanceWlList {
    }
    interface IntrinsicElements {
        "pathar-ambulance-wl-list": PatharAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pathar-ambulance-wl-list": LocalJSX.PatharAmbulanceWlList & JSXBase.HTMLAttributes<HTMLPatharAmbulanceWlListElement>;
        }
    }
}
